#!/bin/bash

# xprintidle gxmessage hibernate-script

# the user running this script must have sudo access
# to the "hibernate" command without passwd
# "%wheel ALL=(ALL) NOPASSWD: /usr/bin/hibernate"
# change "wheel" to "users" if the user doesn't have wheel access



# Fall back to xmessage if gxmessage isn't available
XMESSAGE=$(which gxmessage) || XMESSAGE=xmessage

# 1hr=3600000ms
# error in bash but ok in zsh about float number
# SETTIME=$(( 1.5 * 60 * 60 * 1000 ))
SETTIME=$(awk 'BEGIN {print 1.5 * 60 * 60 * 1000}')

# maximum 1 minute load average for hibernate
MAXLOADAVG=2

# programs that should prohibit hibernate
PROHIBITS=(prohibit-hibernate
           emerge
           make
           cmake
           gcc
           genkernel)

# command executed
COMMAND="sudo hibernate"



# infinite loop for hibernate
while true ; do
   sleep 60
   idletime=$(xprintidle)
   if (( $idletime > $SETTIME )); then
       hibernate=1
   fi
   if (( $(ps aux | grep -c activate-hibernate) > 1 )); then
       hibernate=1
   fi
   if (( $hibernate )); then
      # check the current 1 min loadaverage
      loadavg=$(cat /proc/loadavg | cut -c 1)
      if (( $loadavg < $MAXLOADAVG )); then
          (( lowload++ ))
      else
          lowload=0
      fi
      if (( $lowload > 2)); then
          for each in $PROHIBITS[@] ; do
               if (( $(ps aux | grep -c $each) > 1 )); then
                   hibernate=0
                   break
               fi
          done
          if (( $hibernate )); then
              # reset variables
              lowload=0
              idletime=0
              hibernate=0
              pkill -inf activate-hibernate
              $XMESSAGE -timeout 30 \
                        The system will sleep in 30 seconds, \
                        press esc to abort.
              if (( ! $? )); then
                  eval "$COMMAND"
              fi
          fi
      fi
   fi
done
